[21-Sep-2019 12:44:17 Europe/Berlin] PHP Notice:  Undefined variable: modelFactory in C:\xampp\htdocs\Router\Router.php on line 35
[21-Sep-2019 12:44:17 Europe/Berlin] PHP Stack trace:
[21-Sep-2019 12:44:17 Europe/Berlin] PHP   1. {main}() C:\xampp\htdocs\index.php:0
[21-Sep-2019 12:44:17 Europe/Berlin] PHP   2. Router\Router->process() C:\xampp\htdocs\index.php:16
[21-Sep-2019 12:44:17 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Controllers\HomeController::inject() must be an instance of DI\ModelFactory, null given, called in C:\xampp\htdocs\Router\Router.php on line 35 and defined in C:\xampp\htdocs\Controllers\HomeController.php:29
Stack trace:
#0 C:\xampp\htdocs\Router\Router.php(35): Controllers\HomeController->inject(NULL)
#1 C:\xampp\htdocs\index.php(16): Router\Router->process('/home')
#2 {main}
  thrown in C:\xampp\htdocs\Controllers\HomeController.php on line 29
[21-Sep-2019 12:44:26 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Controllers\HomeController::inject() must be an instance of DI\ModelFactory, string given, called in C:\xampp\htdocs\Router\Router.php on line 36 and defined in C:\xampp\htdocs\Controllers\HomeController.php:29
Stack trace:
#0 C:\xampp\htdocs\Router\Router.php(36): Controllers\HomeController->inject('DI\\ModelFactory')
#1 C:\xampp\htdocs\index.php(16): Router\Router->process('/home')
#2 {main}
  thrown in C:\xampp\htdocs\Controllers\HomeController.php on line 29
[21-Sep-2019 12:44:43 Europe/Berlin] PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function DI\ModelFactory::__construct(), 0 passed in C:\xampp\htdocs\Router\Router.php on line 36 and exactly 3 expected in C:\xampp\htdocs\DI\ModelFactory.php:22
Stack trace:
#0 C:\xampp\htdocs\Router\Router.php(36): DI\ModelFactory->__construct()
#1 C:\xampp\htdocs\index.php(16): Router\Router->process('/home')
#2 {main}
  thrown in C:\xampp\htdocs\DI\ModelFactory.php on line 22
[21-Sep-2019 12:56:21 Europe/Berlin] PHP Fatal error:  Access level to Controllers\HomeController::process() must be public (as in class Controllers\aController) in C:\xampp\htdocs\Controllers\HomeController.php on line 15
[21-Sep-2019 12:56:21 Europe/Berlin] PHP Stack trace:
[21-Sep-2019 12:56:21 Europe/Berlin] PHP   1. {main}() C:\xampp\htdocs\index.php:0
[21-Sep-2019 12:56:21 Europe/Berlin] PHP   2. Router\Router->process() C:\xampp\htdocs\index.php:16
[21-Sep-2019 12:56:21 Europe/Berlin] PHP   3. Router\Router->loadClass() C:\xampp\htdocs\Router\Router.php:34
[21-Sep-2019 12:56:21 Europe/Berlin] PHP   4. spl_autoload_call() C:\xampp\htdocs\Router\Router.php:79
[21-Sep-2019 12:56:21 Europe/Berlin] PHP   5. {closure:C:\xampp\htdocs\autoloader.php:3-14}() C:\xampp\htdocs\Router\Router.php:79
[21-Sep-2019 12:56:21 Europe/Berlin] PHP   6. require_once() C:\xampp\htdocs\autoloader.php:12
[21-Sep-2019 12:56:36 Europe/Berlin] PHP Notice:  Undefined property: Router\Router::$db in C:\xampp\htdocs\Router\Router.php on line 79
[21-Sep-2019 12:56:36 Europe/Berlin] PHP Stack trace:
[21-Sep-2019 12:56:36 Europe/Berlin] PHP   1. {main}() C:\xampp\htdocs\index.php:0
[21-Sep-2019 12:56:36 Europe/Berlin] PHP   2. Router\Router->process() C:\xampp\htdocs\index.php:16
[21-Sep-2019 12:56:36 Europe/Berlin] PHP   3. Router\Router->loadClass() C:\xampp\htdocs\Router\Router.php:34
[21-Sep-2019 12:56:36 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Controllers\aController::__construct() must be an instance of Database\Db, null given, called in C:\xampp\htdocs\Router\Router.php on line 79 and defined in C:\xampp\htdocs\Controllers\aController.php:29
Stack trace:
#0 C:\xampp\htdocs\Router\Router.php(79): Controllers\aController->__construct(NULL)
#1 C:\xampp\htdocs\Router\Router.php(34): Router\Router->loadClass('Controllers\\Hom...')
#2 C:\xampp\htdocs\index.php(16): Router\Router->process('/home')
#3 {main}
  thrown in C:\xampp\htdocs\Controllers\aController.php on line 29
[21-Sep-2019 13:02:56 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Controllers\aController::__construct() must be an instance of DI\Container, instance of Database\Db given, called in C:\xampp\htdocs\Router\Router.php on line 79 and defined in C:\xampp\htdocs\Controllers\aController.php:29
Stack trace:
#0 C:\xampp\htdocs\Router\Router.php(79): Controllers\aController->__construct(Object(Database\Db))
#1 C:\xampp\htdocs\Router\Router.php(35): Router\Router->loadClass('Controllers\\Hom...')
#2 C:\xampp\htdocs\index.php(16): Router\Router->process('/home')
#3 {main}
  thrown in C:\xampp\htdocs\Controllers\aController.php on line 29
[21-Sep-2019 13:08:57 Europe/Berlin] PHP Fatal error:  Uncaught Error: Class 'Auth\Auth' not found in C:\xampp\htdocs\DI\Container.php:39
Stack trace:
#0 C:\xampp\htdocs\Controllers\aController.php(40): DI\Container->getAuth()
#1 C:\xampp\htdocs\index.php(15): Controllers\aController->__construct(Object(DI\Container))
#2 {main}
  thrown in C:\xampp\htdocs\DI\Container.php on line 39
[21-Sep-2019 13:11:00 Europe/Berlin] PHP Fatal error:  Uncaught Error: Class 'Auth\Auth' not found in C:\xampp\htdocs\DI\Container.php:39
Stack trace:
#0 C:\xampp\htdocs\Controllers\aController.php(40): DI\Container->getAuth()
#1 C:\xampp\htdocs\index.php(15): Controllers\aController->__construct(Object(DI\Container))
#2 {main}
  thrown in C:\xampp\htdocs\DI\Container.php on line 39
[21-Sep-2019 13:11:16 Europe/Berlin] PHP Fatal error:  Uncaught Error: Class 'Auth\Auth' not found in C:\xampp\htdocs\DI\Container.php:39
Stack trace:
#0 C:\xampp\htdocs\Controllers\aController.php(40): DI\Container->getAuth()
#1 C:\xampp\htdocs\index.php(15): Controllers\aController->__construct(Object(DI\Container))
#2 {main}
  thrown in C:\xampp\htdocs\DI\Container.php on line 39
[21-Sep-2019 13:11:44 Europe/Berlin] PHP Fatal error:  Uncaught Error: Class 'Auth\Auth' not found in C:\xampp\htdocs\DI\Container.php:40
Stack trace:
#0 C:\xampp\htdocs\Controllers\aController.php(40): DI\Container->getAuth()
#1 C:\xampp\htdocs\index.php(15): Controllers\aController->__construct(Object(DI\Container))
#2 {main}
  thrown in C:\xampp\htdocs\DI\Container.php on line 40
[21-Sep-2019 13:12:11 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: Return value of DI\Container::getAuth() must be an instance of Auth\Auth, none returned in C:\xampp\htdocs\DI\Container.php:43
Stack trace:
#0 C:\xampp\htdocs\Controllers\aController.php(40): DI\Container->getAuth()
#1 C:\xampp\htdocs\index.php(15): Controllers\aController->__construct(Object(DI\Container))
#2 {main}
  thrown in C:\xampp\htdocs\DI\Container.php on line 43
[21-Sep-2019 13:12:29 Europe/Berlin] PHP Fatal error:  Uncaught Error: Class 'Auth\Auth' not found in C:\xampp\htdocs\DI\Container.php:43
Stack trace:
#0 C:\xampp\htdocs\Controllers\aController.php(40): DI\Container->getAuth()
#1 C:\xampp\htdocs\index.php(15): Controllers\aController->__construct(Object(DI\Container))
#2 {main}
  thrown in C:\xampp\htdocs\DI\Container.php on line 43
[21-Sep-2019 13:12:47 Europe/Berlin] PHP Fatal error:  Uncaught Error: Class 'Auth\Auth' not found in C:\xampp\htdocs\DI\Container.php:43
Stack trace:
#0 C:\xampp\htdocs\Controllers\aController.php(40): DI\Container->getAuth()
#1 C:\xampp\htdocs\index.php(15): Controllers\aController->__construct(Object(DI\Container))
#2 {main}
  thrown in C:\xampp\htdocs\DI\Container.php on line 43
[21-Sep-2019 13:12:53 Europe/Berlin] PHP Fatal error:  Uncaught Error: Class 'Auth\Auth' not found in C:\xampp\htdocs\DI\Container.php:43
Stack trace:
#0 C:\xampp\htdocs\Controllers\aController.php(40): DI\Container->getAuth()
#1 C:\xampp\htdocs\index.php(15): Controllers\aController->__construct(Object(DI\Container))
#2 {main}
  thrown in C:\xampp\htdocs\DI\Container.php on line 43
[21-Sep-2019 13:19:16 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Models\aBaseModel::__construct() must be an instance of Auth\Auth, null given, called in C:\xampp\htdocs\DI\ModelFactory.php on line 31 and defined in C:\xampp\htdocs\Models\aBaseModel.php:25
Stack trace:
#0 C:\xampp\htdocs\DI\ModelFactory.php(31): Models\aBaseModel->__construct(NULL, NULL, NULL)
#1 C:\xampp\htdocs\Controllers\HomeController.php(24): DI\ModelFactory->createRegistrationModel()
#2 C:\xampp\htdocs\Router\Router.php(36): Controllers\HomeController->process(Array)
#3 C:\xampp\htdocs\index.php(16): Router\Router->process('/home')
#4 {main}
  thrown in C:\xampp\htdocs\Models\aBaseModel.php on line 25
[21-Sep-2019 16:30:00 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Models\aBaseModel::__construct() must be an instance of Auth\Auth, null given, called in C:\xampp\htdocs\DI\ModelFactory.php on line 31 and defined in C:\xampp\htdocs\Models\aBaseModel.php:25
Stack trace:
#0 C:\xampp\htdocs\DI\ModelFactory.php(31): Models\aBaseModel->__construct(NULL, NULL, NULL)
#1 C:\xampp\htdocs\Controllers\HomeController.php(24): DI\ModelFactory->createRegistrationModel()
#2 C:\xampp\htdocs\Router\Router.php(36): Controllers\HomeController->process(Array)
#3 C:\xampp\htdocs\index.php(16): Router\Router->process('/home')
#4 {main}
  thrown in C:\xampp\htdocs\Models\aBaseModel.php on line 25
[21-Sep-2019 16:33:51 Europe/Berlin] PHP Fatal error:  Uncaught Error: Class 'Auth\Auth' not found in C:\xampp\htdocs\DI\Container.php:43
Stack trace:
#0 C:\xampp\htdocs\DI\Container.php(72): DI\Container->getAuth()
#1 C:\xampp\htdocs\Controllers\HomeController.php(24): DI\Container->getModelFactory()
#2 C:\xampp\htdocs\Router\Router.php(36): Controllers\HomeController->process(Array)
#3 C:\xampp\htdocs\index.php(16): Router\Router->process('/home')
#4 {main}
  thrown in C:\xampp\htdocs\DI\Container.php on line 43
[21-Sep-2019 16:34:07 Europe/Berlin] PHP Fatal error:  Uncaught Error: Class 'Auth\Auth' not found in C:\xampp\htdocs\DI\Container.php:40
Stack trace:
#0 C:\xampp\htdocs\DI\Container.php(71): DI\Container->getAuth()
#1 C:\xampp\htdocs\Controllers\HomeController.php(24): DI\Container->getModelFactory()
#2 C:\xampp\htdocs\Router\Router.php(36): Controllers\HomeController->process(Array)
#3 C:\xampp\htdocs\index.php(16): Router\Router->process('/home')
#4 {main}
  thrown in C:\xampp\htdocs\DI\Container.php on line 40
[21-Sep-2019 16:34:26 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Models\aBaseModel::__construct() must be an instance of Auth\Auth, null given, called in C:\xampp\htdocs\DI\ModelFactory.php on line 31 and defined in C:\xampp\htdocs\Models\aBaseModel.php:25
Stack trace:
#0 C:\xampp\htdocs\DI\ModelFactory.php(31): Models\aBaseModel->__construct(NULL, Object(Database\Db), Object(Helpers\Sessions\Session))
#1 C:\xampp\htdocs\Controllers\HomeController.php(24): DI\ModelFactory->createRegistrationModel()
#2 C:\xampp\htdocs\Router\Router.php(36): Controllers\HomeController->process(Array)
#3 C:\xampp\htdocs\index.php(16): Router\Router->process('/home')
#4 {main}
  thrown in C:\xampp\htdocs\Models\aBaseModel.php on line 25
[21-Sep-2019 16:34:52 Europe/Berlin] PHP Fatal error:  Uncaught Error: Class 'Auth\Auth' not found in C:\xampp\htdocs\DI\Container.php:40
Stack trace:
#0 C:\xampp\htdocs\DI\Container.php(72): DI\Container->getAuth()
#1 C:\xampp\htdocs\Controllers\HomeController.php(24): DI\Container->getModelFactory()
#2 C:\xampp\htdocs\Router\Router.php(36): Controllers\HomeController->process(Array)
#3 C:\xampp\htdocs\index.php(16): Router\Router->process('/home')
#4 {main}
  thrown in C:\xampp\htdocs\DI\Container.php on line 40
[21-Sep-2019 16:36:23 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Models\aBaseModel::__construct() must be an instance of Auth\Auth, null given, called in C:\xampp\htdocs\DI\ModelFactory.php on line 31 and defined in C:\xampp\htdocs\Models\aBaseModel.php:25
Stack trace:
#0 C:\xampp\htdocs\DI\ModelFactory.php(31): Models\aBaseModel->__construct(NULL, Object(Database\Db), Object(Helpers\Sessions\Session))
#1 C:\xampp\htdocs\Controllers\HomeController.php(24): DI\ModelFactory->createRegistrationModel()
#2 C:\xampp\htdocs\Router\Router.php(36): Controllers\HomeController->process(Array)
#3 C:\xampp\htdocs\index.php(16): Router\Router->process('/home')
#4 {main}
  thrown in C:\xampp\htdocs\Models\aBaseModel.php on line 25
[21-Sep-2019 16:37:09 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Models\aBaseModel::__construct() must be an instance of Auth\Auth, instance of Helpers\Auth\Auth given, called in C:\xampp\htdocs\DI\ModelFactory.php on line 31 and defined in C:\xampp\htdocs\Models\aBaseModel.php:25
Stack trace:
#0 C:\xampp\htdocs\DI\ModelFactory.php(31): Models\aBaseModel->__construct(Object(Helpers\Auth\Auth), Object(Database\Db), Object(Helpers\Sessions\Session))
#1 C:\xampp\htdocs\Controllers\HomeController.php(24): DI\ModelFactory->createRegistrationModel()
#2 C:\xampp\htdocs\Router\Router.php(36): Controllers\HomeController->process(Array)
#3 C:\xampp\htdocs\index.php(16): Router\Router->process('/home')
#4 {main}
  thrown in C:\xampp\htdocs\Models\aBaseModel.php on line 25
[21-Sep-2019 18:18:01 Europe/Berlin] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Controllers\aController::__construct() must be an instance of DI\Container, instance of DI\ModelFactory given, called in C:\xampp\htdocs\Router\Router.php on line 79 and defined in C:\xampp\htdocs\Controllers\aController.php:34
Stack trace:
#0 C:\xampp\htdocs\Router\Router.php(79): Controllers\aController->__construct(Object(DI\ModelFactory))
#1 C:\xampp\htdocs\Router\Router.php(35): Router\Router->loadClass('Controllers\\Hom...')
#2 C:\xampp\htdocs\index.php(16): Router\Router->process('/home')
#3 {main}
  thrown in C:\xampp\htdocs\Controllers\aController.php on line 34
